import { Download, Copy, Check, Mail, ChevronDown } from 'lucide-react'
import { useState, useRef, useEffect } from 'react'
import { cn, flattenObject, escapeHtml } from '@/lib/utils'
import { useToast } from './Toast'

interface ExportButtonProps {
  data: any
  label?: string
  filename?: string
}

export default function ExportButton({ data, label = 'Export', filename = 'mailtools-result' }: ExportButtonProps) {
  const [copied, setCopied] = useState(false)
  const [open, setOpen] = useState(false)
  const { toast } = useToast()
  const ref = useRef<HTMLDivElement>(null)

  // Close dropdown on outside click
  useEffect(() => {
    if (!open) return
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [open])

  const close = (fn?: () => void) => () => {
    fn?.()
    setOpen(false)
  }

  const copyJSON = async () => {
    try {
      await navigator.clipboard.writeText(JSON.stringify(data, null, 2))
      setCopied(true)
      toast('Copied to clipboard', 'success')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast('Failed to copy', 'error')
    }
  }

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${filename}.json`
    a.click()
    URL.revokeObjectURL(url)
    toast('Downloaded JSON file', 'success')
  }

  const downloadCSV = () => {
    if (!data || typeof data !== 'object') return
    const flat = flattenObject(data)
    const headers = Object.keys(flat)
    const values = Object.values(flat).map(v => String(v ?? ''))
    const csv = [headers.join(','), values.map(v => `"${v.replace(/"/g, '""')}"`).join(',')].join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${filename}.csv`
    a.click()
    URL.revokeObjectURL(url)
    toast('Downloaded CSV file', 'success')
  }

  const downloadPDF = () => {
    if (!data || typeof data !== 'object') return
    const flat = flattenObject(data)
    const rows = Object.entries(flat)
      .map(([key, value]) => `<tr><td style="padding:6px 12px;font-weight:600;border-bottom:1px solid #e5e7eb;">${escapeHtml(key)}</td><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;font-family:monospace;">${escapeHtml(String(value ?? ''))}</td></tr>`)
      .join('')
    const html = `<!DOCTYPE html>
<html><head><title>${escapeHtml(filename)}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;margin:40px;color:#1a1a1a;}h1{font-size:20px;margin-bottom:4px;}p{color:#666;font-size:12px;margin-top:0;}table{width:100%;border-collapse:collapse;margin-top:16px;}@media print{body{margin:20px;}}</style>
</head><body>
<h1>${escapeHtml(filename)}</h1>
<p>Exported from MailForge · ${new Date().toLocaleString()}</p>
<table>${rows}</table>
<script>window.onload=()=>{setTimeout(()=>window.print(),300);}</script>
</body></html>`
    const w = window.open('', '_blank')
    if (w) {
      w.document.write(html)
      w.document.close()
      toast('PDF print dialog opened', 'info')
    } else {
      toast('Pop-up blocked — allow pop-ups for this site', 'error')
    }
  }

  const emailReport = async () => {
    if (!data || typeof data !== 'object') return
    const flat = flattenObject(data)
    const rows = Object.entries(flat)
      .map(([key, value]) => `<tr><td style="padding:8px 12px;font-weight:600;border-bottom:1px solid #e5e7eb;background:#f9fafb;">${escapeHtml(key)}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-family:monospace;">${escapeHtml(String(value ?? ''))}</td></tr>`)
      .join('')
    const html = `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;max-width:640px;margin:0 auto;">
<h2 style="margin:0 0 4px;">📋 ${escapeHtml(filename)}</h2>
<p style="color:#6b7280;font-size:12px;margin:0 0 16px;">Generated by MailForge · ${new Date().toLocaleString()}</p>
<table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">${rows}</table>
</div>`
    try {
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/html': new Blob([html], { type: 'text/html' }),
          'text/plain': new Blob([`MailTools Report: ${filename}\n\n${Object.entries(flat).map(([k, v]) => `${k}: ${v ?? ''}`).join('\n')}`], { type: 'text/plain' })
        })
      ])
      toast('HTML report copied — paste into your email client', 'success')
    } catch {
      toast('Failed to copy — try using PDF export instead', 'error')
    }
  }

  const menuItems = [
    { label: 'Copy JSON', icon: Check, action: close(copyJSON), color: copied ? 'text-success' : '' },
    { label: 'Download JSON', icon: Download, action: close(downloadJSON) },
    { label: 'Download CSV', icon: Download, action: close(downloadCSV) },
    { label: 'Print / PDF', icon: Download, action: close(downloadPDF) },
    { label: 'Email Report', icon: Mail, action: close(emailReport) },
  ]

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-surface border border-border text-text-secondary hover:text-text-primary hover:border-border-hover transition-all"
      >
        <Download className="w-3.5 h-3.5" />
        {label}
        <ChevronDown className={cn('w-3 h-3 transition-transform', open && 'rotate-180')} />
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-1 w-48 py-1 rounded-xl bg-surface border border-border shadow-xl shadow-black/20 z-50 animate-fade-in">
          {menuItems.map((item) => {
            const Icon = item.icon
            return (
              <button
                key={item.label}
                onClick={item.action}
                className="w-full flex items-center gap-2.5 px-3 py-2 text-xs font-medium text-text-secondary hover:text-text-primary hover:bg-surface-hover transition-colors text-left"
              >
                <Icon className={cn('w-3.5 h-3.5', item.color || 'text-text-muted')} />
                {item.label}
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}


